import {useEffect,useRef,useState} from "react";
import {Archive,FolderUp,RefreshCw,ShieldCheck} from "lucide-react";

type Row=Record<string,any>;
const call=async(path:string,init?:RequestInit)=>{const r=await fetch(path,init);const text=await r.text();let data;try{data=JSON.parse(text)}catch{data=text}if(!r.ok)throw new Error(data?.detail||String(data));return data};
const terminal=(s:string)=>["completed","failed","cancelled","interrupted"].includes(s);

export function ProjectManager({onAuditReady}:{onAuditReady:()=>void}){
 const [health,setHealth]=useState<Row>({}),[jobs,setJobs]=useState<Row[]>([]),[job,setJob]=useState<Row|null>(null),[mode,setMode]=useState<"zip"|"folder">("zip"),[file,setFile]=useState<File|null>(null),[files,setFiles]=useState<File[]>([]),[name,setName]=useState(""),[repoId,setRepoId]=useState(""),[snapshot,setSnapshot]=useState(()=>new Date().toISOString().slice(0,19).replace(/[-:T]/g,"")),[version,setVersion]=useState("main"),[replace,setReplace]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState("");const folderRef=useRef<HTMLInputElement>(null);
 const load=async()=>{const [h,j]=await Promise.all([fetch("/api/health").then(async r=>{try{return await r.json()}catch{return{status:"unavailable"}}}).catch(()=>({status:"unavailable"})),call("/api/repositories/index-jobs")]);setHealth(h);setJobs(j);if(job){const fresh=j.find((x:Row)=>x.id===job.id);if(fresh)setJob(fresh)}else if(j.length)setJob(j[0])};
 useEffect(()=>{load()},[]);useEffect(()=>{if(!job||terminal(job.status))return;const t=setInterval(load,2000);return()=>clearInterval(t)},[job?.id,job?.status]);
 const choose=(f:File|null)=>{setFile(f);if(f&&!name){const n=f.name.replace(/\.zip$/i,"").replace(/[^A-Za-z0-9._-]/g,"-");setName(n);setRepoId(n)}};
 const submit=async()=>{setError("");setBusy(true);try{if(!name||!repoId)throw new Error("请填写项目目录名和项目 ID");const form=new FormData();form.append("repository_directory",name);form.append("replace_existing",String(replace));let upload:Row;if(mode==="zip"){if(!file)throw new Error("请选择 ZIP 项目文件");form.append("zip_file",file,file.name);upload=await call("/api/repositories/upload-zip",{method:"POST",body:form})}else{if(!files.length)throw new Error("请选择项目目录");files.forEach(f=>form.append("files",f,(f as any).webkitRelativePath||f.name));upload=await call("/api/repositories/upload",{method:"POST",body:form})}const created=await call("/api/repositories/index-jobs",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({repository_id:repoId,repository_name:name,repository_path:upload.repository_path,snapshot_id:snapshot,version})});setJob(created);await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const action=async(kind:"resume"|"cancel"|"recover-stale")=>{if(!job)return;try{setJob(await call(`/api/repositories/index-jobs/${job.id}/${kind}`,{method:"POST"}))}catch(e:any){setError(e.message)}};
 return <div className="projectPage"><section className="infra">{[["open_search","OpenSearch","正文 / BM25"],["qdrant","Qdrant","向量召回"],["neo4j","Neo4j","符号 / 调用关系"],["joern","Joern","CPG / 数据流"]].map(([key,label,note])=><article key={key}><i className={health[key]==="available"?"up":"down"}/><div><b>{label}</b><small>{note}</small></div><span>{health[key]||"检测中"}</span></article>)}</section><div className="projectGrid"><section className="panel importer"><div className="panelTitle"><b>导入新项目</b><span>导入 → 固定快照 → 四架构索引</span></div><div className="mode"><button className={mode==="zip"?"active":""} onClick={()=>setMode("zip")}><Archive/>ZIP 文件</button><button className={mode==="folder"?"active":""} onClick={()=>setMode("folder")}><FolderUp/>项目目录</button></div>{mode==="zip"?<label className="drop"><input type="file" accept=".zip" onChange={e=>choose(e.target.files?.[0]||null)}/><FolderUp/><b>{file?.name||"选择项目 ZIP"}</b><span>最大 200 MB，安全解压且拒绝符号链接和路径穿越</span></label>:<label className="drop"><input ref={folderRef} type="file" multiple {...({webkitdirectory:""} as any)} onChange={e=>{const xs=Array.from(e.target.files||[]);setFiles(xs);if(xs[0])choose(new File([],((xs[0] as any).webkitRelativePath||"project").split("/")[0]))}}/><FolderUp/><b>{files.length?`${files.length} 个文件`:"选择项目目录"}</b><span>保持浏览器提供的相对目录结构</span></label>}<div className="projectForm"><label>项目目录名<input value={name} onChange={e=>setName(e.target.value)} placeholder="sinkspring-bench-all-main"/></label><label>项目 ID<input value={repoId} onChange={e=>setRepoId(e.target.value)} placeholder="sinkspring-bench-all"/></label><label>快照 ID<input value={snapshot} onChange={e=>setSnapshot(e.target.value)}/></label><label>版本<input value={version} onChange={e=>setVersion(e.target.value)}/></label></div><label className="replace"><input type="checkbox" checked={replace} onChange={e=>setReplace(e.target.checked)}/>替换同名的已上传目录</label>{error&&<p className="error">{error}</p>}<button className="startIndex" disabled={busy} onClick={submit}>{busy?"正在上传…":"上传并建立索引"}</button></section><section className="panel jobPanel"><div className="panelTitle"><b>索引任务</b><button className="icon" onClick={load}><RefreshCw/></button></div>{job?<Job job={job}/>:<div className="empty">上传项目后，这里会实时显示每个索引阶段。</div>}{job&&<div className="jobActions">{["failed","interrupted","cancelled"].includes(job.status)&&<button onClick={()=>action("resume")}>续跑索引</button>}{["queued","running"].includes(job.status)&&<button onClick={()=>action("cancel")}>取消</button>}{job.lease_state==="expired"&&<button onClick={()=>action("recover-stale")}>恢复失联</button>}{job.status==="completed"&&<button className="auditReady" onClick={onAuditReady}><ShieldCheck/>开始安全审计</button>}</div>}<h3>最近任务</h3><div className="jobList">{jobs.slice(0,8).map(j=><button className={job?.id===j.id?"active":""} key={j.id} onClick={()=>setJob(j)}><b>{j.request?.repository_id}</b><span>{j.stage}</span><em>{j.status}</em></button>)}</div></section></div></div>
}

function Job({job}:{job:Row}){const history=job.stage_history||[];return <div className="job"><div className="jobStatus"><span className={job.status}/><div><b>{job.request?.repository_name||job.request?.repository_id}</b><small>#{String(job.id).slice(0,8)} · {job.status}</small></div></div><div className="currentStage">{job.stage}</div><div className="stageHistory">{history.map((h:Row,i:number)=><div key={i} className={i===history.length-1?"current":"done"}><i/><span>{h.stage}</span><small>{h.time?new Date(h.time).toLocaleTimeString():""}</small></div>)}</div>{job.result&&<pre>{JSON.stringify(job.result,null,2)}</pre>}{job.error&&<p className="error">{job.error}</p>}</div>}
