"""审计业务依赖的能力契约，不依赖HTTP、SQLite或OpenSearch。"""

from contextlib import AbstractContextManager
from pathlib import Path
from typing import Any, Protocol


class SourceSnapshotPort(Protocol):
    def capture(self, root: Path, repository_id: str, version_label: str) -> str: ...
    def indexing_directory(self, snapshot_id: str) -> AbstractContextManager[str]: ...
    def bind(self, source_snapshot_id: str, repository_id: str,
             snapshot_id: str, index_run_id: str) -> None: ...


class AuditModelPort(Protocol):
    def next_action(self, messages: list[dict[str, str]]) -> dict[str, Any]: ...


class EvidenceToolsPort(Protocol):
    def close(self) -> None: ...
    def call(self, name: str, arguments: dict[str, Any]) -> dict[str, Any]: ...


class AuditStorePort(Protocol):
    def create(self, request: dict[str, Any]) -> dict[str, Any]: ...
    def get(self, task_id: str) -> dict[str, Any]: ...
    def list(self) -> list[dict[str, Any]]: ...
    def update(self, task_id: str, **fields: Any) -> dict[str, Any]: ...
